### ISSUE TITLE
Migrate realtimebus.tis.bz.it

### ISSUE THREAD

**Issue by bertolla** [idm-suedtirol/realtimebus#46]
related idm-suedtirol/geobank#17
- [x] reduce TTL of realtimebus.tis.bz.it
- [x] switch dns entry
- [x] check if everything works correctly   
- [x] point bus.meran.eu to new ip

**Comment by bertolla** [comment]
@idm-suedtirol/ict-automation 
Check if all sites dependent of realtimebus point to the ip in ireland and are still working correctly
34.253.90.105

**Comment by rcavaliere** [comment]
Checked bus.bz.it, mobility.meran.eu (in all declinations), everything looks OK!
