### ISSUE TITLE
As a maintainer of the whole realtimebus infrastructure, I would like to set up a new testing server for starting the installation of the new server application based on Node JS

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/realtimebus#47]
Task externalized to Rampanelli. The label "blocked" can be removed once once the internal budget decision has been taken.

**Comment by rcavaliere** [comment]
@bertolla setup information prepared by Rampanelli (see attached). 
Can you set up a new machine with these instructions by 21.12.2018, when a meeting with him is foreseen?

[181214_AWSServer-SetupInfo.pdf](https://github.com/idm-suedtirol/realtimebus/files/2680654/181214_AWSServer-SetupInfo.pdf)

**Comment by bertolla** [comment]
Server is working as https://realtimebusv2.sasabus.org and https://mobility.meran.eu/alpha already points to it.

**Comment by bertolla** [comment]
@rcavaliere Can we move this user-story from testing?

**Comment by rcavaliere** [comment]
@bertolla  No, I would wait for SASA to configure their server to the new end-point so to check that the real-time positions are correctly displayed.
